# Generated by Django 4.0.6 on 2023-05-23 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_received', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('proficiency_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technologies_used', models.CharField(max_length=100)),
                ('github_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_employer', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('subscription', models.BooleanField(default=False)),
                ('subscription_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('website', models.CharField(blank=True, max_length=50)),
                ('github', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior'), ('Principal', 'Principal'), ('C-level', 'C-level'), ('VP', 'VP'), ('Director', 'Director'), ('Manager', 'Manager')], default='Mid-level', max_length=50)),
                ('work_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Apprenticeship', 'Apprenticeship')], default='Full-time', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('new_profile', models.BooleanField(default=True)),
                ('open_to_work', models.BooleanField(default=True)),
                ('open_to_relocation', models.BooleanField(default=True)),
                ('open_to_remote', models.BooleanField(default=True)),
                ('notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('available_for_remote_work', models.BooleanField(default=False)),
                ('preferred_working_hours', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=50)),
                ('stripe_subscription_status', models.CharField(blank=True, max_length=50)),
                ('stripe_subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_cancel_at_period_end', models.BooleanField(default=False)),
                ('stripe_subscription_cancel_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_created', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_current_period_start', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_current_period_end', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_days_until_due', models.PositiveIntegerField(blank=True, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_invoice_status', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_invoice_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('hired', models.BooleanField(default=False)),
                ('hired_date', models.DateTimeField(blank=True, null=True)),
                ('hired_by_name', models.CharField(blank=True, max_length=50, null=True)),
                ('currently_interesting', models.BooleanField(default=False)),
                ('awards', models.ManyToManyField(blank=True, to='accounts.award')),
                ('hired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('languages', models.ManyToManyField(blank=True, to='accounts.languageproficiency')),
                ('preferred_tech_stack', models.ManyToManyField(blank=True, to='accounts.technology')),
                ('project_contributions', models.ManyToManyField(blank=True, to='accounts.project')),
                ('publications', models.ManyToManyField(blank=True, to='accounts.publication')),
                ('skills', models.ManyToManyField(blank=True, to='accounts.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
