import Navbar from '@/components/Constants/Navbar'
import '../globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Constants/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Public page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
     <div className={inter.className}>
        <Navbar />
        {children}
        <Footer />
     </div>
  )
}
